version: '3.8'

services:
  mysql_db:
    image: mysql:8
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: sushi
      MYSQL_USER: test
      MYSQL_PASSWORD: test123
    volumes:
      - "./migrations/init.sql:/docker-entrypoint-initdb.d/001.sql"